// <auto-generated />
using System;
using HenriJervsonGrainWarehouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HenriJervsonGrainWarehouse.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230314221451_seeddata2")]
    partial class seeddata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HenriJervsonGrainWarehouse.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EnteringMass")
                        .HasColumnType("float");

                    b.Property<double?>("LeavingMass")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Cargo");
                });
#pragma warning restore 612, 618
        }
    }
}
